- name: Create restricted user admin
  hosts: all
  become: true
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Create user "{{ admin_username }}"
      user:
        name: "{{ admin_username }}"
        groups: sudo
        shell: /bin/bash
        create_home: yes

    - name: Create .ssh dir
      file:
        path: "/home/{{ admin_username }}/.ssh"
        state: directory
        owner: "{{ admin_username }}"
        group: "{{ admin_username }}"
        mode: '0700'

    - name: Set public key
      copy:
        src: "{{ admin_pubkey_file }}"
        dest: "/home/{{ admin_username }}/.ssh/authorized_keys"
        owner: "{{ admin_username }}"
        group: "{{ admin_username }}"
        mode: '0600'

    - name: Перезапустить SSH
      service:
        name: ssh
        state: restarted