- name: Create restricted user admin
  hosts: all
  become: true
  vars_files:
    - ../group_vars/all.yml
  tasks:
    - name: Create user "{{ admin_username }}"
      user:
        name: "{{ admin_username }}"
        groups: sudo
        shell: /bin/bash
        create_home: yes

    - name: Create .ssh dir
      file:
        path: "/home/{{ admin_username }}/.ssh"
        state: directory
        owner: "{{ admin_username }}"
        group: "{{ admin_username }}"
        mode: '0700'

    - name: Убедиться, что файл authorized_keys существует
      file:
        path: "/home/{{ admin_username }}/.ssh/authorized_keys"
        state: touch
        owner: "{{ admin_username }}"
        group: "{{ admin_username }}"
        mode: '0600'

    - name: Добавить публичный ключ для admin, если его ещё нет
      lineinfile:
        path: "/home/{{ admin_username }}/.ssh/authorized_keys"
        line: "{{ lookup('file', admin_pubkey_file) }}"
        create: yes
        owner: "{{ admin_username }}"
        group: "{{ admin_username }}"
        mode: '0600'
        state: present
        insertafter: EOF

    - name: Создать тестовый файл для теста от имени admin
      copy:
        dest: "/home/{{ admin_username }}/example.txt"
        content: "Пример файла, созданного Ansible"
        owner: "{{ admin_username }}"
        group: "{{ admin_username }}"
        mode: '0644'

    - name: Перезапустить SSH
      service:
        name: ssh
        state: restarted